<?php
/**
 * @category    design
 * @package     accessshop_default
 * @copyright   Copyright (c) 2015 Access Keys (http://www.access-keys.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * 
 */
?>

<?php $_product = Mage::registry('product'); ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $_product->getProductUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Main Product Info') ?></a></p>
</div>
