<?php
/**
 * @category    design
 * @package     accessshop_default
 * @copyright   Copyright (c) 2015 Access Keys (http://www.access-keys.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="container">
    <div class="row">
        <div class="col-sm-9 left-links">
            <div class="row">
                <div class="col-sm-3 block-footer-cmslinks">
                    <?php echo $this->getChildHtml('footer-cmslinks'); ?>
                </div>
                <div class="col-sm-3 block-footer-cmslinks">
                    <?php echo $this->getChildHtml('footer-cmslinks1'); ?>
                </div>
                <div class="col-sm-3 block-footer-recent-products">
                    <?php echo $this->getChildHtml('footer_newsletter'); ?>
                </div>
                <div class="col-sm-3 block-footer-contact-info">
                    <?php echo $this->getChildHtml('footer-contact-info'); ?>
                </div>
            </div>
        </div>
        <div class="col-sm-3 right-links">
            <div class="block-footer-social">
                <?php echo $this->getChildHtml('footer-social'); ?>
            </div>
            <div class="block-footer-cards">
                <?php echo $this->getChildHtml('footer-cards'); ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="block-footer-company">
                <?php echo $this->getChildHtml('footer-company'); ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8 block-copyright pull-left">
            <?php echo $this->getCopyright(); ?>
        </div>
        <div class="col-sm-4 block-footer-bottom-right-links pull-right">
            <?php //echo $this->getChildHtml('footer-bottom-right-links'); ?>
        </div>
    </div>
    <div id="back_top" style="display: block;"></div>
</div>
