<?php
/**
 * @category    design
 * @package     accessshop_default
 * @copyright   Copyright (c) 2015 Access Keys (http://www.access-keys.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="block block-leftnav">
	<div class="block-title">
		<strong>
			<?php echo $this->__('Categories') ?>
		</strong>
	</div>
	<div class="block-content">
		<div >
            <ul class="sidenav-cat" id="home-side-menu">
    			<?php foreach ($this->getStoreCategories() as $_category): ?>
    				<?php if($_category->name!=""): ?>
    					<?php echo $this->drawItem($_category); ?>
    				<?php endif?>
    			<?php endforeach ?>
    		</ul>
        </div>
	</div>
</div>